### ISSUE TITLE
Would it be possible to share the Python script as well?

### ISSUE THREAD

**Issue by frankrolf** [grillitype/ProofGenerator#2]
It is very convenient to have a drag-and-drop application for the Proof Generator, but this also makes debugging very hard.
I just tried to use ProofGenerator for the first time, and something’s failing somewhere. Where? No idea.
All I see (in Console.app):
```
fault	21:38:23.483074+0100	ProofGenerator	Failed to get Metal shader cache main folder: mkdir failed to create compiler cache path (errno = 2)

```

If I had a way to run the tool from the command line, I could help fixing the problem.

**Comment by KatjaSchimmel** [comment]
Just uploaded the Python Script. You can use it via the command line with: _python ProofGenerator.py [path to font file]_ 

Let me know if this issue had to do with the App or the ProofGenerator Script itself.
